# KCC Deployment Configuration
# Type:         Compute Firewall
# Description:  Manifest used to create Compute Firewalls in a project.
# Maintainer:   Cloud Platform Ops <CloudPlatforms@bestbuy.com>

apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewall
metadata:
  name: gke-nodes-rule1
spec:
  direction: EGRESS
  enableLogging: true
  description: "Allow GKE nodes 80/443 outbound"
  allow:
    - protocol: tcp
      ports:
      - "80"
      - "443"
  targetTags:
  - gke-nodes
  priority: 800
  networkRef:
    name: {{ $.Values.network | replace " " "-" | lower }}
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewall
metadata:
  name: gke-nodes-rule2
spec:
  direction: EGRESS
  enableLogging: true
  description: "Firewall rule allowing internal access for GKE"
  allow:
    - protocol: all
  targetTags:
  - gke-nodes
  destinationRanges:
  - 
  priority: 800
  networkRef:
    name: {{ $.Values.network | replace " " "-" | lower }}

