# KCC Deployment Configuration
# Type:         Compute Firewall
# Description:  Manifest used to create Compute Firewalls in a project.
# Maintainer:   Cloud Platform Ops <CloudPlatforms@bestbuy.com>

apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewall
metadata:
  name: mgmt-host-rule1
spec:
  direction: EGRESS
  enableLogging: true
  description: "Allow 80/443 outbound"
  allow:
    - protocol: tcp
      ports:
      - "80"
      - "443"
  targetTags:
  - management-hosts
  priority: 800
  networkRef:
    name: {{ $.Values.network | replace " " "-" | lower }}
