{{ $project_hash := ((lookup "v1" "ConfigMap" $.Release.Namespace $.Release.Namespace)|default .Values.global.lookups).data.bby_kcc_project_hash }}
{{ $bby_environment := ((lookup "v1" "ConfigMap" $.Release.Namespace $.Release.Namespace)|default .Values.global.lookups).data.bby_environment }}
# KCC Deployment Configuration
# Type:         IAMServiceAccount
# Description:  Manifest used to create IAM Service Accounts in a project.
# Maintainer:   Cloud Platform Ops <CloudPlatforms@bestbuy.com>

apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: gke-{{ $.Values.name | replace " " "-" | lower }}-{{ $project_hash }}
  labels:
    bby_environment: "{{ $bby_environment }}"
    bby_project_id: "{{ $.Release.Namespace }}"
    bby_kcc_project_hash: "{{ $project_hash }}"
spec:
  displayName: GKE Service Account
