# KCC Deployment Configuration
# Type:         ComputeSubnetwork
# Description:  Manifest used to create Compute Subnetworks in a project.
# Maintainer:   Cloud Platform Ops <CloudPlatforms@bestbuy.com>

apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  labels:
    subnet: gke
  name: {{ $.Values.subnetwork | replace " " "-" | lower }}
spec:
  logConfig:
    aggregationInterval: INTERVAL_5_SEC
    flowSampling: 0.5
    metadata: INCLUDE_ALL_METADATA
  ipCidrRange: 
  region: us-central1
  description: GKE
  privateIpGoogleAccess: true
  networkRef:
    name: {{ $.Values.network }}
  secondaryIpRange:
  - ipCidrRange: 
    rangeName: gke-pods
  - ipCidrRange: 
    rangeName: gke-services
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  labels:
    subnet: mgmt
  name: {{ $.Values.mgmthost.subnetwork | replace " " "-" | lower }}
spec:
  logConfig:
    aggregationInterval: INTERVAL_5_SEC
    flowSampling: 0.5
    metadata: INCLUDE_ALL_METADATA
  ipCidrRange: 
  region: us-central1
  description: mgmt
  privateIpGoogleAccess: true
  networkRef:
    name: {{ $.Values.network }}
